apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: taxi-source-topic
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 1 
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: taxi-trip-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  partitions: 12
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: taxi-producer
  name: taxi-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taxi-producer
    spec:
      containers:
      - name: taxi-producer
        image: adamcattermole/taxi-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: taxi-source-topic
          - name: LOG_LEVEL
            value: "INFO"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: trip-producer
  name: trip-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: trip-producer
    spec:
      containers:
      - name: trip-producer
        image: adamcattermole/trip-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: SOURCE_TOPIC
            value: taxi-source-topic
          - name: SINK_TOPIC
            value: taxi-trip-topic
          - name: GROUP_ID
            value: trip-producer
          - name: LOG_LEVEL
            value: "INFO"